[package]
name = "kek"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
libm = "0.1.4"
image = "0.24.9"
minifb = "0.25.0"
csv ="1.3.0"
rayon = "1.9.0"
faer = "0.17"
[dependencies.sdl2]
version = "0.35.2"
features = [ "unsafe_textures"]
